export enum bloodGroup{
    aPositive= 'A+',
    aNegative= 'A-',
    bPositive= 'B+',
    bNegative= 'B-',
    // oPositive= 'O+',
    // oNegative= 'O-',
    // a1Positive= 'A1+',
    // a1Negative= 'A1-',
    // b1Positive= 'B1+',
    // a1bpositive= 'A1B+',
    // a1bNegative= 'A1B-',
    // a2positive= 'A2-',
    // a2bpositive= 'A2B+',
    // a2bNegative= 'A2B-',
} 